version: "3.7"

services: 
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres    

  redis:
    image: redis:6.2.0-alpine
    ports: 
      - 6379:6379
      
  app: 
    build: .
    container_name: rentx
    ports: 
      - 3333:3333
      - 9229:9229 
    volumes:
      - .:/usr/app
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  pgdata: 
    driver: local